package com.ayutaki.chinjufumod.main;

import net.minecraftforge.fml.common.ModMetadata;

public class ChinjufuModInfoCore {

	public static void registerInfo(ModMetadata meta) {
		meta.modId = Reference.MOD_ID;
		meta.name = Reference.MOD_NAME;
		meta.description = "This is 'KantaiCollection' Fan Mod. KantaiCollection(DMM GAMES) http://www.dmm.com/netgame/feature/kancolle.html";
		meta.version = Reference.MOD_VERSION;
		meta.url = "https://www.curseforge.com/minecraft/mc-mods/chinjufumod ChinjufuMod_wiki http://chinjufumod.wicurio.com/ My Blog http://ch.nicovideo.jp/ayutaki_s";
		meta.authorList.add("Ayutaki Shou");
		meta.credits = "Thank you to those who are publishing MOD source code and those who upload maiking MOD videos.";
		meta.logoFile = "";
		meta.autogenerated = false;
	}

}
